<?php
declare(strict_types=1);

namespace Tests;

use Psr\Container\ContainerInterface;
use WoohooLabs\Harmony\Harmony;

abstract class TestCase extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Harmony
     */
    private $app;

    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * Bootstrap the application for each test.
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->app = require __DIR__ . '/../bootstrap/app.php';
        $this->container = $container;
    }

    /**
     * @return ContainerInterface
     */
    public function getContainer(): ContainerInterface
    {
        return $this->container;
    }

    /**
     * @return Harmony
     */
    public function getApp(): Harmony
    {
        return $this->app;
    }
}
